papers:
  wisconsin-weekly-blade:
    title: Wisconsin Weekly Blade
    path: wisconsin-weekly-blade
    base_url: https://pages.dangerouspress.org/wisconsin-weekly-blade
    sources:
    - type: jp2 
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn84025842
  phoenix-tribune:
    title: Phoenix Tribune
    path: phoenix-tribune
    base_url: https://pages.dangerouspress.org/phoenix-tribune
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn96060881
  denver-star:
    title: Denver Star
    path: denver-star
    base_url: https://pages.dangerouspress.org/denver-star
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn84025887
  omaha-monitor:
    title: Omaha Monitor
    path: omaha-monitor
    base_url: https://pages.dangerouspress.org/omaha-monitor
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: 00225879
  nashville-globe:
    title: Nashville Globe
    path: nashville-globe
    base_url: https://pages.dangerouspress.org/nashville-globe
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn86064259
  wichita-searchlight:
    title: Wichita Searchlight
    path: wichita-searchlight
    base_url: https://pages.dangerouspress.org/wichita-searchlight
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn85032585
  baltimore-afro-american:
    title: Baltimore Afro-American
    path: baltimore-afro-american
    base_url: https://pages.dangerouspress.org/baltimore-afro-american
    sources:
    - type: pdf
      folder: /Users/nealcaren/Library/CloudStorage/OneDrive-UniversityofNorthCarolinaatChapelHill/Documents/black-press-downloads/baltimoreafroamerican_pdfs_processed
      sample_filename: 1910-01-01_01.pdf
  athens-republique:
    title: Athens Republique
    path: athens-republique
    base_url: https://pages.dangerouspress.org/athens-republique
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: "2012233098"
  broad-ax:
    title: Broad Ax
    path: broad-ax
    base_url: https://pages.dangerouspress.org/broad-ax
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn84024055
  chicago-defender:
    title: Chicago Defender
    path: chicago-defender
    base_url: https://pages.dangerouspress.org/chicago-defender
    sources:
    - type: pdf
      folder: /Volumes/Lightning/chronicling-america/pq-defender/defender_pdfs/Defender_PDFs
      sample_filename: Chicago-Defender_1909-07-31.pdf
  chicago-whip:
    title: Chicago Whip
    path: chicago-whip
    base_url: https://pages.dangerouspress.org/chicago-whip
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn86056950
  cleveland-advocate:
    title: Cleveland Advocate
    path: cleveland-advocate
    base_url: https://pages.dangerouspress.org/cleveland-advocate
    sources:
    - type: pdf
      folder: /Users/nealcaren/Library/CloudStorage/OneDrive-UniversityofNorthCarolinaatChapelHill/black-press/cleveland-advoate_pdfs
      sample_filename: advocate_1926-01-29.pdf
  cleveland-gazette:
    title: Cleveland Gazette
    path: cleveland-gazette
    base_url: https://pages.dangerouspress.org/cleveland-gazette
    sources:
    - type: pdf
      folder: /Users/nealcaren/Library/CloudStorage/OneDrive-UniversityofNorthCarolinaatChapelHill/black-press/cleveland-gazette_pdfs
      sample_filename: cleveland+gazette_1910-03-19.pdf
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn83035387
  colorado-statesman:
    title: Colorado Statesman
    path: colorado-statesman
    base_url: https://pages.dangerouspress.org/colorado-statesman
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn83025514
  denver-star:
    title: Denver Star
    path: denver-star
    base_url: https://pages.dangerouspress.org/denver-star
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn84025887
  indianapolis-freeman:
    title: Indianapolis Freeman
    path: indianapolis-freeman
    base_url: https://pages.dangerouspress.org/indianapolis-freeman
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn82016211
  kansas-city-sun:
    title: Kansas City Sun
    path: kansas-city-sun
    base_url: https://pages.dangerouspress.org/kansas-city-sun
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn90061556
  new-york-age:
    title: New York Age
    path: new-york-age
    base_url: https://pages.dangerouspress.org/new-york-age
    sources:
    - type: pdf
      folder: /Users/nealcaren/Library/CloudStorage/OneDrive-UniversityofNorthCarolinaatChapelHill/black-press/new-york-age_pdfs
      sample_filename: new-york-age_1906-10-04.pdf
  omaha-monitor:
    title: Omaha Monitor
    path: omaha-monitor
    base_url: https://pages.dangerouspress.org/omaha-monitor
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: 00225879
  raleigh-independent:
    title: Raleigh Independent
    path: raleigh-independent
    base_url: https://pages.dangerouspress.org/raleigh-independent
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn92072995
  richmond-planet:
    title: Richmond Planet
    path: richmond-planet
    base_url: https://pages.dangerouspress.org/richmond-planet
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn84025841
  springfield-forum:
    title: Springfield Forum
    path: springfield-forum
    base_url: https://pages.dangerouspress.org/springfield-forum
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn86086415
  st-louis-argus:
    title: St. Louis Argus
    path: st-louis-argus
    base_url: https://pages.dangerouspress.org/st-louis-argus
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/argus/
      lccn: argus_downloads
  st-paul-appeal:
    title: St. Paul Appeal
    path: st-paul-appeal
    base_url: https://pages.dangerouspress.org/st-paul-appeal
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn83016810
  tulsa-star:
    title: Tulsa Star
    path: tulsa-star
    base_url: https://pages.dangerouspress.org/tulsa-star
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn86064118
  washington-bee:
    title: Washington Bee
    path: washington-bee
    base_url: https://pages.dangerouspress.org/washington-bee
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/argus/
      lccn: bee_downloads
  washington-tribune:
    title: Washington Tribune
    path: washington-tribune
    base_url: https://pages.dangerouspress.org/washington-tribune
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn87062236
  houston-informer:
    title: Houston Informer
    path: houston-informer
    base_url: https://pages.dangerouspress.org/houston-informer
    sources:
    - type: preoptimized_jpg
      folder: /Volumes/Lightning/chronicling-america/houston-informer
  dallas-express:
    title: Dallas Express
    path: dallas-express
    base_url: https://pages.dangerouspress.org/dallas-express
    sources:
    - type: preoptimized_jpg
      folder: /Volumes/Lightning/chronicling-america/dallas-express
  western-outlook:
    title: Western Outlook
    path: western-outlook
    base_url: https://pages.dangerouspress.org/western-outlook
    sources:
    - type: preoptimized_jpg
      folder: /Volumes/Lightning/chronicling-america/western-outlook
  iowa-bystander:
    title: Iowa Bystander
    path: iowa-bystander
    base_url: https://pages.dangerouspress.org/iowa-bystander
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn83025186
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn85049804
  twin-city-star:
    title: Twin City Star
    path: twin-city-star
    base_url: https://pages.dangerouspress.org/twin-city-star
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn90060427
  montana-plaindealer:
    title: Montana Plaindealer
    path: montana-plaindealer
    base_url: https://pages.dangerouspress.org/montana-plaindealer
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn84036199
  muskogee-cimeter:
    title: Muskogee Cimeter
    path: muskogee-cimeter
    base_url: https://pages.dangerouspress.org/muskogee-cimeter
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn83025060
  pittsburgh-courier:
    title: Pittsburgh Courier
    path: pittsburgh-courier
    base_url: https://pages.dangerouspress.org/pittsburgh-courier
    sources:
    - type: pdf
      folder: /Volumes/Lightning/chronicling-america/pq-defender/courier_pdfs
      sample_filename: Pittsburgh-Courier_1911-03-25.pdf
      recursive: false  # Only scan root directory, ignore subdirectories with split pages
  portland-new-age:
    title: Portland New Age
    path: portland-new-age
    base_url: https://pages.dangerouspress.org/portland-new-age
    sources:
    - type: jp2
      root: /Volumes/Lightning/chronicling-america/loc_downloads/
      lccn: sn83025107
storage:
  provider: cloudflare-r2
  bucket: african-american-press-archive
  account_id: ae978df95b073e0e6a0d595c996900ca
  endpoint: https://ae978df95b073e0e6a0d595c996900ca.r2.cloudflarestorage.com
  public_base: https://pages.dangerouspress.org
