name = "dangerouspress"
main = "src/index.ts"
compatibility_date = "2025-01-01"
workers_dev = true

# Custom domain
routes = [
  { pattern = "beta.dangerouspress.org", custom_domain = true }
]

# Run OCR indexer hourly
[triggers]
crons = ["0 * * * *"]

[assets]
directory = "./src/public/"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "dangerouspress-db"
database_id = "399bcc68-1807-49c8-8d15-c8cc6ae57f13"

[[r2_buckets]]
binding = "R2"
bucket_name = "dangerouspress-pages"
